title = "Shop front demonstration"
pluralizelisttitles = false
[params]
	email = "hendry+shop@iki.fi"
	currency = "SGD" # ISO 4217
[taxonomies]
	category = "categories"
	vendor = "vendors"
	tag = "tags"
