title = "The new Alaska Guys shop"
pluralizelisttitles = false
enableRobotsTXT = true
# baseURL is needed for successUrl/cancelUrl redirection from Stripe
baseURL = "https://shop.thealaskaguys.com"
[params]
	email = "hendry+alaskaguys@iki.fi"
	currency = "SGD" # ISO 4217
	stripe = "pk_test_1amuSFIBwCaicwoNGifewy4a"
[taxonomies]
	tag = "tags"
[outputs]
	page = ["html","json"]
	section = ["html","json"]
	home = ["html","json"]
